version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
    groups:
      github-actions-routine:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
    target-branch: "dev"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
    groups:
      pip-routine:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      pip-major:
        patterns:
          - "*"
        update-types:
          - "major"
    target-branch: "dev"
